export const RBT_TALENTS = [
  // 🧠 ASSESSMENT
  {
    id: "data_eye",
    branch: "assessment",
    tier: 1,
    title: "Data Eye",
    description: "Reveal behavior trends earlier during data tasks.",
    cost: 1,
    requires: [],
  },
  {
    id: "function_finder",
    branch: "assessment",
    tier: 2,
    title: "Function Finder",
    description: "Improve accuracy when identifying function of behavior.",
    cost: 1,
    requires: ["data_eye"],
  },
  {
    id: "graph_master",
    branch: "assessment",
    tier: 3,
    title: "Graph Master",
    description: "Unlock advanced graph interpretation.",
    cost: 1,
    requires: ["function_finder"],
  },
  {
    id: "functional_precision",
    branch: "assessment",
    tier: 4,
    title: "Functional Precision",
    description: "Bonus XP when assessments are error-free.",
    cost: 1,
    requires: ["graph_master"],
    milestone: true,
  },

  // 🎯 INTERVENTION
  {
    id: "reinforcement_architect",
    branch: "intervention",
    tier: 1,
    title: "Reinforcement Architect",
    description: "Unlock advanced reinforcement options.",
    cost: 1,
    requires: [],
  },
  {
    id: "prompt_strategist",
    branch: "intervention",
    tier: 2,
    title: "Prompt Strategist",
    description: "Improve prompt hierarchy decisions.",
    cost: 1,
    requires: ["reinforcement_architect"],
  },
  {
    id: "chaining_specialist",
    branch: "intervention",
    tier: 3,
    title: "Chaining Specialist",
    description: "Unlock chaining modules early.",
    cost: 1,
    requires: ["prompt_strategist"],
    unlocksModules: ["sap_chaining"],
  },
  {
    id: "errorless_mastery",
    branch: "intervention",
    tier: 4,
    title: "Errorless Mastery",
    description: "First error does not count during teaching.",
    cost: 1,
    requires: ["chaining_specialist"],
    milestone: true,
  },

  // 🧭 ETHICS
  {
    id: "ethical_compass",
    branch: "ethics",
    tier: 1,
    title: "Ethical Compass",
    description: "Spot ethical violations faster.",
    cost: 1,
    requires: [],
  },
  {
    id: "family_liaison",
    branch: "ethics",
    tier: 2,
    title: "Family Liaison",
    description: "Unlock caregiver communication scenarios.",
    cost: 1,
    requires: ["ethical_compass"],
  },
  {
    id: "crisis_control",
    branch: "ethics",
    tier: 3,
    title: "Crisis Control",
    description: "Unlock crisis simulations.",
    cost: 1,
    requires: ["family_liaison"],
  },
  {
    id: "lead_technician",
    branch: "ethics",
    tier: 4,
    title: "Lead Technician",
    description: "Prepare for professional leadership roles.",
    cost: 1,
    requires: ["crisis_control"],
    milestone: true,
  },
];
