import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export async function exportStudyLogPDF({ hero }) {
  const progress = hero.studyProgress || {};

  const rows = Object.entries(progress)
    .map(([date, data]) => {
      const count = data.sessionsCompleted?.length || 0;
      return `<tr><td>${date}</td><td>${count}</td></tr>`;
    })
    .join("");

  const html = `
    <html>
      <body>
        <h1>Study Log</h1>
        <p><strong>Hero:</strong> ${hero.name}</p>
        <p><strong>Specialization:</strong> RBT</p>

        <table border="1" cellpadding="6" cellspacing="0">
          <tr>
            <th>Date</th>
            <th>Sessions Completed</th>
          </tr>
          ${rows}
        </table>

        <p style="margin-top:20px;">
          Generated by Hero App
        </p>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });

  await Sharing.shareAsync(uri, {
    mimeType: "application/pdf",
    dialogTitle: "Study Log PDF",
  });
}
